#!/bin/sh -e

unzip JetBrainsMono.zip
unzip DejaVuSansMono.zip

find ./ -name '*Windows*' -exec rm -rf {} +

install -dm755          "$1/usr/share/fonts/TTF"
install -Dm644 -- *.ttf "$1/usr/share/fonts/TTF"
